job_config:
  class: SlurmSequentialJob
  jobname: bench_linalg
  task:
    type: CommandCall
    command: python
    command_line_args:
    - ${PROJECT_DIR}/benchmark/benchmark.py
    - --modules
    - modules: null
    - --mod_q
    - mod_q: null
    - --max_time
    - max_time: null
    - --sectors
    - sectors: null
    shell: true
  script_template: slurm_benchmark_threads.sh
  requirements_slurm:
    time: 0-12:00:00
    mem: 30G
    partition: cpu
    nodes: 1
    cpus-per-task: 32
    mail-type: FAIL
    nodelist: anderson[01-24]
  options:
    environment_setup: 'eval "$(micromamba shell hook --shell bash )"

      micromamba activate "${PROJECT_DIR}/env_conda"

      # export TENPY_OPTIMIZE=3

      '
  change_parameters:
    expansion: product
    recursive_keys:
    - legs
    - mod_q
modules:
- tensordot_npc
- combine_npc
- split_npc
- tensordot_numpy
max_time: 0.1
mod_q:
- []
- - 1
sectors: 10
legs:
- 1
- 2
- 3
